# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name="Movie's title"),
        ),
    ]
